### ISSUE TITLE
[Bug 0008] Issues when teacher stop releasing

### ISSUE THREAD

**Issue by tom6311tom6311** [NTU-NMLAB/iTeach#39]
- Author: TA
- Assignee: TA
- Dev Owner:
- Status: New
- Environment: e80151a2375977008eb21c805c094e3f6e1fb8e7
- Reproduce Steps
    1. 以兩台Simulator開啟iTeach，一為老師一為學生
    2. 老師開啟選單上任一課程，並開始發布
    3. 學生搜尋課程
    4. 老師停止發佈
- Expected Result
    - 在`4.`後，學生那邊應開看不到老師本來發佈的課程
- Actual Result
    - 在`4.`後，學生那邊還可以看到老師本來發佈的課程，而且還可以加入

**Comment by victoresque** [comment]
這個功能在 #37 中實作了，請問要合並到這個 PR 嗎
