### ISSUE TITLE
[Bug 0012] 重新安裝App發生白頻

### ISSUE THREAD

**Issue by tom6311tom6311** [NTU-NMLAB/iTeach#47]
Author: @tom6311tom6311
Assignee: @stationaryfront 
Dev Owner:
Status: New
Environment: a253eecfbd4c8287b5a88eff749283229dc92137
Reproduce Steps:
1. 刪除iTeach並重新安裝
2. 開啟iTeach App

Expected Results:  
進到Login視窗  

Actual Results:  
白頻  

Notes:  
或許是因為移除ClassMenu的mock data後，影響到一開始的Navigation state判斷？

**Comment by stationaryfront** [comment]
應該是，晚點修一下QQ

**Comment by stationaryfront** [comment]
@tom6311tom6311 #42 應該好了麻煩你再看一下><
